#!/usr/bin/env python3
"""Build the multi-map package: one header per map plus the index.

Each map's data is emitted under its own prefix with a MapDescriptor tying it
together; the index includes them all, lists them for the menu, and defines
the MAPS_MAX_* bounds that size the EWRAM arenas. Constants that the code
compiles in -- the luxel shift, the shade table shape, the shared luxel pad --
are checked equal across maps here, because a mismatch would not fail the
build, it would misrender.

Usage: generate_maps.py <map.bsp> [more.bsp ...]
"""
import pathlib, sys

import extract_bsp_wireframe as E

LUXEL_PAD = 1 << 18          # shared across maps so BSP_LUXEL_MASK is one constant


def main(paths):
    out_dir = pathlib.Path("src/generated")
    out_dir.mkdir(exist_ok=True)
    stats = {}
    for path in paths:
        name = pathlib.Path(path).stem
        stats[name] = E.extract(
            path, out_dir / f"map_{name}.h", None,
            mip=1, lmscale=16, lmgain=100, concave_merge=True,
            prefix=name, luxel_pad=LUXEL_PAD)
    shared = {k: {s[k] for s in stats.values()}
              for k in ("luxel_shift", "shade_rows", "shade_shift")}
    for key, values in shared.items():
        if len(values) != 1:
            raise SystemExit(f"maps disagree on {key}: {values}")

    lines = ["/* Generated by generate_maps.py; do not edit. */",
             "#ifndef MAPS_INDEX_H", "#define MAPS_INDEX_H",
             f"#define BSP_LUXEL_MASK 0x{LUXEL_PAD - 1:x}u",
             "enum {",
             f"    BSP_LUXEL_SHIFT = {shared['luxel_shift'].pop()},",
             f"    BSP_SHADE_ROWS = {shared['shade_rows'].pop()},",
             f"    BSP_SHADE_SHIFT = {shared['shade_shift'].pop()},",
             f"    BSP_MAP_COUNT = {len(stats)},"]
    for key, label in (("vertices", "VERTICES"), ("edges", "EDGES"),
                       ("faces", "FACES"), ("leaves", "LEAVES"),
                       ("nodes", "NODES"), ("entities", "ENTITIES"),
                       ("textures", "TEXTURES")):
        lines.append(f"    MAPS_MAX_{label} = "
                     f"{max(s[key] for s in stats.values())},")
    lines.append("};")
    for name in stats:
        lines.append(f'#include "map_{name}.h"')
    lines.append("static const MapDescriptor *const bsp_maps[BSP_MAP_COUNT] = {")
    for name in stats:
        lines.append(f"    &{name}_map,")
    lines.append("};")
    lines.append("#endif")
    (out_dir / "maps_index.h").write_text("\n".join(lines) + "\n")
    print(f"maps_index.h: {len(stats)} maps, "
          f"max faces {max(s['faces'] for s in stats.values())}, "
          f"max vertices {max(s['vertices'] for s in stats.values())}")


if __name__ == "__main__":
    main(sys.argv[1:])
