#!/usr/bin/env python3
"""Generate deterministic 32-pixel piecewise-perspective cube commands."""
import math
import pathlib
import sys

W, H, FOCAL = 240, 160, 128.0
FRAMES, MAX_COMMANDS = 24, 12
ATLAS = [(0, 0), (32, 0), (64, 0), (0, 32), (32, 32), (64, 32)]


def mat(angle):
    ay, ax = angle, angle * 0.73
    cy, sy, cx, sx = math.cos(ay), math.sin(ay), math.cos(ax), math.sin(ax)
    # Ry * Rx, object to camera.
    return ((cy, sy * sx, sy * cx),
            (0.0, cx, -sx),
            (-sy, cy * sx, cy * cx))


def transpose_mul(r, v):
    return tuple(sum(r[j][i] * v[j] for j in range(3)) for i in range(3))


def ray(x, y):
    return ((x - 120.0) / FOCAL, (y - 80.0) / FOCAL, 1.0)


def hit_for_face(r, x, y, forced_face=None):
    o = transpose_mul(r, (0.0, 0.0, -4.0))
    d = transpose_mul(r, ray(x, y))
    if forced_face is None:
        near, far, face = -1e30, 1e30, 0
        for axis in range(3):
            if abs(d[axis]) < 1e-9:
                if not -1.0 <= o[axis] <= 1.0:
                    return None
                continue
            a, b = (-1.0 - o[axis]) / d[axis], (1.0 - o[axis]) / d[axis]
            fa, fb = axis * 2, axis * 2 + 1
            if a > b:
                a, b, fa, fb = b, a, fb, fa
            if a > near:
                near, face = a, fa
            far = min(far, b)
            if near > far:
                return None
        if far < 0:
            return None
        t = near if near >= 0 else far
    else:
        face = forced_face
        axis, side = face // 2, -1.0 if (face & 1) == 0 else 1.0
        if abs(d[axis]) < 1e-9:
            return None
        t = (side - o[axis]) / d[axis]
    p = tuple(o[i] + t * d[i] for i in range(3))
    axis = face // 2
    if axis == 0:
        a, b = p[2], -p[1]
    elif axis == 1:
        a, b = p[0], p[2]
    else:
        a, b = p[0], -p[1]
    # A fixed 32-pixel span can straddle a cube-face edge. Clamp the chosen
    # face's extrapolated endpoints to its atlas panel instead of sampling the
    # black padding/another face; the edge is corrected at the next span.
    a, b = max(-1.0, min(1.0, a)), max(-1.0, min(1.0, b))
    ox, oy = ATLAS[face]
    # Keep a texel border inside each 32x32 face panel.
    return face, ox + 1.0 + (a + 1.0) * 14.5, oy + 1.0 + (b + 1.0) * 14.5


def clamp16(v):
    return max(-32768, min(32767, int(round(v))))


def line_commands(r, y):
    samples = [hit_for_face(r, x + 0.5, y + 0.5) for x in range(W)]
    hits = [h is not None for h in samples]
    if not any(hits):
        return 0, []
    left, right = hits.index(True), W - hits[::-1].index(True)
    # Split first at actual face edges.
    raw, start = [], left
    while start < right:
        face = samples[start][0]
        end = start + 1
        while end < right and samples[end][0] == face:
            end += 1
        raw.append([start, end, face])
        start = end
    # Four register writes cannot service face slivers only a few pixels wide.
    # Fold <8-pixel runs into a neighbour, then subdivide long runs to <=32.
    i = 0
    while i < len(raw):
        if raw[i][1] - raw[i][0] >= 8 or len(raw) == 1:
            i += 1
        elif i:
            raw[i - 1][1] = raw[i][1]
            raw.pop(i)
        else:
            raw[1][0] = raw[0][0]
            raw.pop(0)
    ranges = []
    for a, b, face in raw:
        width = b - a
        pieces = max(1, (width + 31) // 32)
        for k in range(pieces):
            p0 = a + (width * k) // pieces
            p1 = a + (width * (k + 1)) // pieces
            ranges.append((p0, p1, face))
    cmds = []
    for a, b, face in ranges[:MAX_COMMANDS]:
        ha = hit_for_face(r, a + 0.5, y + 0.5, face)
        hb = hit_for_face(r, b - 0.5, y + 0.5, face)
        du = (hb[1] - ha[1]) / max(1, b - a - 1)
        dv = (hb[2] - ha[2]) / max(1, b - a - 1)
        pa, pc = clamp16(du * 256.0), clamp16(dv * 256.0)
        # BG2X/Y are references for screen x=0 even when written at x0.
        bgx = int(round(ha[1] * 256.0)) - pa * int(a + 0.5)
        bgy = int(round(ha[2] * 256.0)) - pc * int(a + 0.5)
        cmds.append((a * 4, pa, pc, 0, bgx, bgy))
    return (left << 8) | right, cmds


def generate():
    frames = []
    for f in range(FRAMES):
        r = mat(2.0 * math.pi * f / FRAMES)
        frames.append([line_commands(r, y) for y in range(H)])
    return frames


def emit(path):
    frames = generate()
    out = ["/* Generated by scripts/generate_cube.py; do not edit. */",
           "#ifndef CUBE_FRAMES_H", "#define CUBE_FRAMES_H", ""]
    out.append(f"enum {{ CUBE_FRAME_COUNT = {FRAMES} }};")
    out.append("static const CubeFrame cube_frames[CUBE_FRAME_COUNT] = {")
    for frame in frames:
        out.append("  { .line = {")
        for winh, cmds in frame:
            padded = cmds + [(0, 0, 0, 0, 0, 0)] * (MAX_COMMANDS - len(cmds))
            cs = ", ".join("{%d,%d,%d,%d,%d,%d}" % c for c in padded)
            out.append(f"    {{0x{winh:04x},{len(cmds)},{{{cs}}}}},")
        out.append("  }},")
    out += ["};", "", "#endif"]
    pathlib.Path(path).write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    emit(sys.argv[1])
