#!/usr/bin/env python3
"""Generate lookup tables used by the runtime fixed-point cube renderer."""

import math
import pathlib
import sys


def emit(path):
    sine = [round(math.sin(2.0 * math.pi * i / 256.0) * (1 << 14))
            for i in range(256)]
    # q is 16.16 inverse depth. The Q24 reciprocal converts (u/z)/q to
    # a Q8 texture coordinate with one multiply and a shift by 16.
    reciprocal = [0] + [min(65535, (1 << 24) // q) for q in range(1, 32768)]
    clipping_reciprocal = [0] + [(1 << 24) // value
                                  for value in range(1, 32768)]
    projection_reciprocal = [0] + [min(65535, (1 << 16) // depth)
                                    for depth in range(1, 4096)]

    lines = [
        "/* Generated by scripts/generate_runtime_luts.py; do not edit. */",
        "#ifndef RUNTIME_CUBE_LUTS_H",
        "#define RUNTIME_CUBE_LUTS_H",
        "static const int16_t sine_q14[256] = {",
    ]
    for start in range(0, len(sine), 16):
        lines.append("    " + ", ".join(map(str, sine[start:start + 16])) + ",")
    lines.append("};")
    lines.append("static const uint16_t reciprocal_q24[32768] = {")
    for start in range(0, len(reciprocal), 16):
        lines.append("    " + ", ".join(
            map(str, reciprocal[start:start + 16])) + ",")
    lines.append("};")
    lines.append("static const uint32_t clipping_reciprocal_q24[32768] = {")
    for start in range(0, len(clipping_reciprocal), 12):
        lines.append("    " + ", ".join(
            map(str, clipping_reciprocal[start:start + 12])) + ",")
    lines.append("};")
    lines.append("static const uint16_t projection_reciprocal_q16[4096] = {")
    for start in range(0, len(projection_reciprocal), 16):
        lines.append("    " + ", ".join(
            map(str, projection_reciprocal[start:start + 16])) + ",")
    lines.append("};")
    lines += ["#endif"]
    pathlib.Path(path).write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    emit(sys.argv[1])
